



import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author muham
 */
public class DataPendaftarPage extends javax.swing.JFrame {

    /**
     * Creates new form DataPendaftar
     */
    public DataPendaftarPage() throws IOException {
        initComponents();
        Pendaftar dataPendaftar = new Pendaftar();
        dataPendaftar.readUserAktif();
        dataPendaftar.readData();
//        mengisi setiap field sesuai database
        namaLengkapField.setText(dataPendaftar.getNama());
        NISNField.setText(dataPendaftar.getNISN());
        alamatField.setText(dataPendaftar.getAlamat());
        kabupatenKotaField.setText(dataPendaftar.getKabupatenKota());
        jenisKelaminField.setText(dataPendaftar.getJenisKelamin());
//       menghilangkan tombol save
        saveButton.setVisible(false);
//        menghilangkan separator
        jSeparatorNamaLengkap.setVisible(false);
        jSeparatorNISN.setVisible(false);
        jSeparatorAlamat.setVisible(false);
        jSeparatorKabupatenKota.setVisible(false);
        jSeparatorJenisKelamin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        logOutLabel = new javax.swing.JLabel();
        akunLabel = new javax.swing.JLabel();
        dataPendaftaranLabel = new javax.swing.JLabel();
        pendaftaranLabel = new javax.swing.JLabel();
        berandaLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        namaLengkapField = new javax.swing.JTextField();
        NISNField = new javax.swing.JTextField();
        alamatField = new javax.swing.JTextField();
        kabupatenKotaField = new javax.swing.JTextField();
        jenisKelaminField = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        headerLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jSeparatorNamaLengkap = new javax.swing.JSeparator();
        jSeparatorNISN = new javax.swing.JSeparator();
        jSeparatorAlamat = new javax.swing.JSeparator();
        jSeparatorKabupatenKota = new javax.swing.JSeparator();
        jSeparatorJenisKelamin = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(242, 237, 215));

        logOutLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logOutLabel.setText("Log Out");
        logOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutLabelMouseClicked(evt);
            }
        });

        akunLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        akunLabel.setText("Akun");
        akunLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                akunLabelMouseClicked(evt);
            }
        });

        dataPendaftaranLabel.setBackground(new java.awt.Color(0, 0, 0));
        dataPendaftaranLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dataPendaftaranLabel.setText("Data Pendaftar");

        pendaftaranLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pendaftaranLabel.setText("Pendaftaran");
        pendaftaranLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendaftaranLabelMouseClicked(evt);
            }
        });

        berandaLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        berandaLabel.setText("Beranda");
        berandaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                berandaLabelMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel20.setText("PPDB Online");

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("|");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel22.setText("Nama Lengkap");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel23.setText("NISN");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel24.setText("Alamat");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel25.setText("Kabupaten/Kota");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel26.setText("Jenis Kelamin");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel27.setText(":");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel28.setText(":");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel29.setText(":");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel30.setText(":");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel31.setText(":");

        namaLengkapField.setEditable(false);
        namaLengkapField.setBackground(new java.awt.Color(242, 237, 215));
        namaLengkapField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        namaLengkapField.setBorder(null);
        namaLengkapField.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                namaLengkapFieldComponentShown(evt);
            }
        });
        namaLengkapField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaLengkapFieldActionPerformed(evt);
            }
        });

        NISNField.setEditable(false);
        NISNField.setBackground(new java.awt.Color(242, 237, 215));
        NISNField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        NISNField.setBorder(null);
        NISNField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NISNFieldActionPerformed(evt);
            }
        });

        alamatField.setEditable(false);
        alamatField.setBackground(new java.awt.Color(242, 237, 215));
        alamatField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        alamatField.setBorder(null);

        kabupatenKotaField.setEditable(false);
        kabupatenKotaField.setBackground(new java.awt.Color(242, 237, 215));
        kabupatenKotaField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        kabupatenKotaField.setBorder(null);

        jenisKelaminField.setEditable(false);
        jenisKelaminField.setBackground(new java.awt.Color(242, 237, 215));
        jenisKelaminField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jenisKelaminField.setBorder(null);

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        headerLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        headerLabel.setText("Data Siswa");

        saveButton.setText("Simpan");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jSeparatorNamaLengkap.setForeground(new java.awt.Color(0, 0, 0));

        jSeparatorNISN.setForeground(new java.awt.Color(0, 0, 0));

        jSeparatorAlamat.setForeground(new java.awt.Color(0, 0, 0));

        jSeparatorKabupatenKota.setForeground(new java.awt.Color(0, 0, 0));

        jSeparatorJenisKelamin.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(berandaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(pendaftaranLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dataPendaftaranLabel)
                        .addGap(18, 18, 18)
                        .addComponent(akunLabel)
                        .addGap(18, 18, 18)
                        .addComponent(logOutLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editButton)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparatorJenisKelamin, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(jSeparatorAlamat)
                                    .addComponent(jSeparatorNamaLengkap)
                                    .addComponent(namaLengkapField, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(NISNField)
                                    .addComponent(alamatField)
                                    .addComponent(kabupatenKotaField)
                                    .addComponent(jenisKelaminField)
                                    .addComponent(jSeparatorNISN)
                                    .addComponent(jSeparatorKabupatenKota))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(headerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logOutLabel)
                    .addComponent(akunLabel)
                    .addComponent(dataPendaftaranLabel)
                    .addComponent(pendaftaranLabel)
                    .addComponent(berandaLabel)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(headerLabel)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel31)
                    .addComponent(namaLengkapField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparatorNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel30)
                    .addComponent(NISNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparatorNISN, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel29)
                    .addComponent(alamatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparatorAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27)
                    .addComponent(kabupatenKotaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorKabupatenKota, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28)
                    .addComponent(jenisKelaminField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(saveButton))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void berandaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaLabelMouseClicked
        BerandaUserPage beranda = new BerandaUserPage();
        beranda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_berandaLabelMouseClicked

    private void pendaftaranLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendaftaranLabelMouseClicked
        PendaftaranPage pendaftaranPage = new PendaftaranPage();
        pendaftaranPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pendaftaranLabelMouseClicked

    private void akunLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akunLabelMouseClicked
        AkunPage akun = null;
        try {
            akun = new AkunPage();
        } catch (IOException ex) {
            Logger.getLogger(DataPendaftarPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        akun.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_akunLabelMouseClicked

    private void namaLengkapFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaLengkapFieldActionPerformed
            
    }//GEN-LAST:event_namaLengkapFieldActionPerformed

    private void namaLengkapFieldComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_namaLengkapFieldComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_namaLengkapFieldComponentShown

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // mengecek data kosong atau tidak
        if(namaLengkapField.getText() != null && NISNField.getText() != null && alamatField.getText() != null && kabupatenKotaField.getText() != null && jenisKelaminField.getText() != null){
            // membuat setiap field dapat diedit
            namaLengkapField.setEditable(true);
            NISNField.setEditable(true);
            alamatField.setEditable(true);
            kabupatenKotaField.setEditable(true);
            jenisKelaminField.setEditable(true);
            // menghilangkan tombol edit
            editButton.setVisible(false);
            // memunculkan tombol edit
            saveButton.setVisible(true);
            // memunculkan separator
            jSeparatorNamaLengkap.setVisible(true);
            jSeparatorNISN.setVisible(true);
            jSeparatorAlamat.setVisible(true);
            jSeparatorKabupatenKota.setVisible(true);
            jSeparatorJenisKelamin.setVisible(true);
            
                
        }else{
            JOptionPane.showMessageDialog(rootPane, "Silahkan melakukan pendaftaran terlebih dahulu!");
        }       
        
    }//GEN-LAST:event_editButtonActionPerformed

    private void NISNFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NISNFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NISNFieldActionPerformed

    private void logOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLabelMouseClicked
        int respon =  JOptionPane.showConfirmDialog(null, "Anda yakin?", "Log Out", OK_CANCEL_OPTION);
       
        if(respon == 0){
            File input = new File("akunAktif.txt");
            input.delete();
            LoginPage login = new LoginPage();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logOutLabelMouseClicked

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // menyimpan data
        Pendaftar updateData = new Pendaftar();
        try {
            boolean sukses = updateData.updateData(namaLengkapField.getText(), NISNField.getText(), alamatField.getText(), kabupatenKotaField.getText(), jenisKelaminField.getText());
            if(sukses){
                JOptionPane.showMessageDialog(rootPane, "Data berhasil diupdate!");
            }else {
                JOptionPane.showMessageDialog(rootPane, "Data gagal diupdate!");
            }
           //  menghilangkan tombol save
            saveButton.setVisible(false);
//        menghilangkan separator
            jSeparatorNamaLengkap.setVisible(false);
            jSeparatorNISN.setVisible(false);
            jSeparatorAlamat.setVisible(false);
            jSeparatorKabupatenKota.setVisible(false);
            jSeparatorJenisKelamin.setVisible(false);
            // membuat field tidak dapat diedit kembali
            namaLengkapField.setEditable(false);
            NISNField.setEditable(false);
            alamatField.setEditable(false);
            kabupatenKotaField.setEditable(false);
            jenisKelaminField.setEditable(false);
            // memunculkan tombol edit
            editButton.setVisible(true);
            // menghilangkan tombol edit
            saveButton.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(DataPendaftarPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPendaftarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPendaftarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPendaftarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPendaftarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DataPendaftarPage().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(DataPendaftarPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NISNField;
    private javax.swing.JLabel akunLabel;
    private javax.swing.JTextField alamatField;
    private javax.swing.JLabel berandaLabel;
    private javax.swing.JLabel dataPendaftaranLabel;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparatorAlamat;
    private javax.swing.JSeparator jSeparatorJenisKelamin;
    private javax.swing.JSeparator jSeparatorKabupatenKota;
    private javax.swing.JSeparator jSeparatorNISN;
    private javax.swing.JSeparator jSeparatorNamaLengkap;
    private javax.swing.JTextField jenisKelaminField;
    private javax.swing.JTextField kabupatenKotaField;
    private javax.swing.JLabel logOutLabel;
    private javax.swing.JTextField namaLengkapField;
    private javax.swing.JLabel pendaftaranLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
